version: "3"

networks:
  tw_net:
    driver: bridge

services:
  proxy:
    image: nginx
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front
      - back
    container_name: tw_proxy
    ports:
      - 80:80
    networks:
      - tw_net
    
  front:
    build:
      context: ./travelweather-client
    image: tw-front:latest
    container_name: tw_front
    expose:
      - 3000
    networks:
      - tw_net

  back:
    build:
      context: ./travelweather
    image: tw-back:latest
    container_name: tw_back
    expose:
      - 8000
    networks:
      - tw_net
